In [11]:
df=pd.read_csv('diabetes_dataset.csv')
df.describe()
df.head(5)

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,Male,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,Type 2,1
1,48,Female,White,Highschool,Middle,Employed,Former,1,143,6.7,...,55,50,30,93,150,2.00,5.63,23.0,No Diabetes,0
2,60,Male,Hispanic,Highschool,Middle,Unemployed,Never,1,57,6.4,...,66,99,36,118,195,5.07,7.51,44.7,Type 2,1
3,74,Female,Black,Highschool,Low,Retired,Never,0,49,3.4,...,50,79,140,139,253,5.28,9.03,38.2,Type 2,1
4,46,Male,White,Graduate,Middle,Retired,Never,1,109,7.2,...,52,125,160,137,184,12.74,7.20,23.5,Type 2,1


In [15]:
import pandas as pd

# 1. Load original dataset
df = pd.read_csv("diabetes_dataset.csv")  # adjust path if needed
# print(df.head())
# 2. Columns that are invasive (blood-test based)
invasive_cols = [
    "cholesterol_total",
    "hdl_cholesterol",
    "ldl_cholesterol",
    "triglycerides",
    "glucose_fasting",
    "glucose_postprandial",
    "insulin_level",
    "hba1c",
]

# 3. Drop invasive features
df_noninvasive = df.drop(columns=invasive_cols)

# 4. Save to a new file
output_path = "diabetes_noninvasive.csv"
df_noninvasive.to_csv(output_path, index=False)

print("New file saved as:", output_path)
print("Shape:", df_noninvasive.shape)
print("Columns:\n", df_noninvasive.columns.tolist())


New file saved as: diabetes_noninvasive.csv
Shape: (100000, 23)
Columns:
 ['age', 'gender', 'ethnicity', 'education_level', 'income_level', 'employment_status', 'smoking_status', 'alcohol_consumption_per_week', 'physical_activity_minutes_per_week', 'diet_score', 'sleep_hours_per_day', 'screen_time_hours_per_day', 'family_history_diabetes', 'hypertension_history', 'cardiovascular_history', 'bmi', 'waist_to_hip_ratio', 'systolic_bp', 'diastolic_bp', 'heart_rate', 'diabetes_risk_score', 'diabetes_stage', 'diagnosed_diabetes']


In [3]:
import pandas as pd
import numpy as np

# 1. Load original dataset
df = pd.read_csv("diabetes_dataset.csv")  # change path if needed

# 2. Columns that are invasive (blood-test based)
invasive_cols = [
    "cholesterol_total",
    "hdl_cholesterol",
    "ldl_cholesterol",
    "triglycerides",
    "glucose_fasting",
    "glucose_postprandial",
    "insulin_level",
    "hba1c",
]

# 3. Drop invasive features
df_noninv = df.drop(columns=invasive_cols)

# 4. Define target columns that we DON'T want to accidentally drop
target_cols = ["diagnosed_diabetes", "diabetes_stage", "diabetes_risk_score"]

# 5. Select numeric feature columns (excluding targets)
numeric_cols = df_noninv.select_dtypes(include=[np.number]).columns
feature_cols = [c for c in numeric_cols if c not in target_cols]

# 6. Correlation matrix on numeric predictors
corr = df_noninv[feature_cols].corr().abs()

# 7. Keep only upper triangle of correlation matrix
upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))

# 8. Choose a threshold and collect features to drop
threshold = 0.85   # you can change this to 0.8 / 0.9 etc.
to_drop_corr = [col for col in upper.columns if any(upper[col] > threshold)]

print("Highly correlated features to drop:", to_drop_corr)

# 9. Drop the highly correlated features
df_reduced = df_noninv.drop(columns=to_drop_corr)

# 10. Save outputs
df_noninv.to_csv("diabetes_noninvasive.csv", index=False)           # only non-invasive
df_reduced.to_csv("diabetes_noninvasive_reduced.csv", index=False)  # + correlation filter

print("Original shape:         ", df.shape)
print("Non-invasive shape:     ", df_noninv.shape)
print("Reduced (no high corr): ", df_reduced.shape)



Highly correlated features to drop: []
Original shape:          (100000, 31)
Non-invasive shape:      (100000, 23)
Reduced (no high corr):  (100000, 23)


In [1]:
import pandas as pd

# 1. Load raw dataset
df = pd.read_csv("diabetes_dataset.csv")  # adjust path if needed

# 2. Invasive (blood-test) features to remove
invasive_cols = [
    "cholesterol_total",
    "hdl_cholesterol",
    "ldl_cholesterol",
    "triglycerides",
    "glucose_fasting",
    "glucose_postprandial",
    "insulin_level",
    "hba1c",
]

# 3. Drop invasive features + extra targets you don't want
drop_cols = invasive_cols + ["diabetes_stage", "diabetes_risk_score"]
df = df.drop(columns=drop_cols)

# 4. Separate target
target_col = "diagnosed_diabetes"
y = df[target_col]
X = df.drop(columns=[target_col])

# 5. One-hot encode categorical predictors
# (object or category dtypes)
X_encoded = pd.get_dummies(X, drop_first=True)

# 6. Reattach target
df_classification = X_encoded.copy()
df_classification[target_col] = y

# 7. Save to new file
output_path = "diabetes_classification_noninvasive.csv"
df_classification.to_csv(output_path, index=False)

print("Saved clean classification dataset to:", output_path)
print("Shape:", df_classification.shape)
print("Columns:\n", df_classification.columns.tolist())


Saved clean classification dataset to: diabetes_classification_noninvasive.csv
Shape: (100000, 33)
Columns:
 ['age', 'alcohol_consumption_per_week', 'physical_activity_minutes_per_week', 'diet_score', 'sleep_hours_per_day', 'screen_time_hours_per_day', 'family_history_diabetes', 'hypertension_history', 'cardiovascular_history', 'bmi', 'waist_to_hip_ratio', 'systolic_bp', 'diastolic_bp', 'heart_rate', 'gender_Male', 'gender_Other', 'ethnicity_Black', 'ethnicity_Hispanic', 'ethnicity_Other', 'ethnicity_White', 'education_level_Highschool', 'education_level_No formal', 'education_level_Postgraduate', 'income_level_Low', 'income_level_Lower-Middle', 'income_level_Middle', 'income_level_Upper-Middle', 'employment_status_Retired', 'employment_status_Student', 'employment_status_Unemployed', 'smoking_status_Former', 'smoking_status_Never', 'diagnosed_diabetes']


In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Load the prepared classification dataset
df = pd.read_csv("diabetes_classification_noninvasive.csv")
print(df.head())
target = "diagnosed_diabetes"
X = df.drop(columns=[target])
y = df[target]

# 2. Train–test split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=0, stratify=y)

# 3. Logistic Regression model (recommended baseline)
logit_clf = Pipeline([
    ("scaler", StandardScaler()),  # scales all numeric/dummy features
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

logit_clf.fit(X_train, y_train)
y_pred_logit = logit_clf.predict(X_test)

print("=== Logistic Regression ===")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred_logit))
print("\nClassification report:\n", classification_report(y_test, y_pred_logit))

# 4. Random Forest model (non-linear, often stronger)
rf_clf = RandomForestClassifier(
    n_estimators=300,
    random_state=0,
    class_weight="balanced",
    n_jobs=-1
)

rf_clf.fit(X_train, y_train)
y_pred_rf = rf_clf.predict(X_test)

print("=== Random Forest ===")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification report:\n", classification_report(y_test, y_pred_rf))


   age  alcohol_consumption_per_week  physical_activity_minutes_per_week  \
0   58                             0                                 215   
1   48                             1                                 143   
2   60                             1                                  57   
3   74                             0                                  49   
4   46                             1                                 109   

   diet_score  sleep_hours_per_day  screen_time_hours_per_day  \
0         5.7                  7.9                        7.9   
1         6.7                  6.5                        8.7   
2         6.4                 10.0                        8.1   
3         3.4                  6.6                        5.2   
4         7.2                  7.4                        5.0   

   family_history_diabetes  hypertension_history  cardiovascular_history  \
0                        0                     0                       0   


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

# 1. Load your prepared classification dataset
df = pd.read_csv("diabetes_classification_noninvasive.csv")

target = "diagnosed_diabetes"
X = df.drop(columns=[target])
y = df[target]

# 2. Train–test split (stratified to keep class ratio)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=0, stratify=y)

# ==============================
# 3. Decision Tree classifier
# ==============================
dt_clf = DecisionTreeClassifier(
    max_depth=6,          # limit depth to reduce overfitting
    min_samples_split=50, # require some samples to split
    random_state=0,
    class_weight="balanced"   # handle class imbalance a bit
)

dt_clf.fit(X_train, y_train)
y_pred_dt = dt_clf.predict(X_test)

print("=== Decision Tree ===")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("\nClassification report:\n", classification_report(y_test, y_pred_dt))

# ==============================
# 4. AdaBoost classifier
# ==============================
# Uses decision stumps (max_depth=1 trees) internally by default
ada_clf = AdaBoostClassifier(
    n_estimators=200,   # number of weak learners
    learning_rate=0.1,
    random_state=0
)

ada_clf.fit(X_train, y_train)
y_pred_ada = ada_clf.predict(X_test)

print("=== AdaBoost ===")
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred_ada))
print("\nClassification report:\n", classification_report(y_test, y_pred_ada))


=== Decision Tree ===
Confusion matrix:
 [[4891 3109]
 [4697 7303]]

Classification report:
               precision    recall  f1-score   support

           0       0.51      0.61      0.56      8000
           1       0.70      0.61      0.65     12000

    accuracy                           0.61     20000
   macro avg       0.61      0.61      0.60     20000
weighted avg       0.62      0.61      0.61     20000



/apps/python/3.10/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


=== AdaBoost ===
Confusion matrix:
 [[2621 5379]
 [2027 9973]]

Classification report:
               precision    recall  f1-score   support

           0       0.56      0.33      0.41      8000
           1       0.65      0.83      0.73     12000

    accuracy                           0.63     20000
   macro avg       0.61      0.58      0.57     20000
weighted avg       0.62      0.63      0.60     20000



In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import make_scorer, recall_score, f1_score

# 1. Load your prepared dataset
df = pd.read_csv("diabetes_classification_noninvasive.csv")

target = "diagnosed_diabetes"
X = df.drop(columns=[target])
y = df[target]

# 2. Define models (you can add others)
models = {
    "logistic": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
    ]),
    "random_forest": RandomForestClassifier(
        n_estimators=300, random_state=0, class_weight="balanced", n_jobs=-1
    ),
    "decision_tree": DecisionTreeClassifier(
        max_depth=6, min_samples_split=50, class_weight="balanced", random_state=0
    ),
    "adaboost": AdaBoostClassifier(
        n_estimators=200, learning_rate=0.1, random_state=0
    ),
}

# 3. CV setup and scoring
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)

scoring = {
    "accuracy": "accuracy",
    "recall_1": make_scorer(recall_score, pos_label=1),
    "f1_1": make_scorer(f1_score, pos_label=1),
}

# 4. Run CV for each model
for name, clf in models.items():
    print(f"\n=== {name} ===")
    scores = cross_validate(clf, X, y, cv=cv, scoring=scoring, n_jobs=-1)

    for metric in scoring.keys():
        vals = scores[f"test_{metric}"]
        print(f"{metric}: {vals.mean():.3f} ± {vals.std():.3f}")



=== logistic ===
accuracy: 0.602 ± 0.001
recall_1: 0.557 ± 0.002
f1_1: 0.627 ± 0.001

=== random_forest ===
accuracy: 0.625 ± 0.002
recall_1: 0.839 ± 0.003
f1_1: 0.728 ± 0.001

=== decision_tree ===
accuracy: 0.599 ± 0.006
recall_1: 0.568 ± 0.019
f1_1: 0.630 ± 0.011

=== adaboost ===


/apps/python/3.10/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/apps/python/3.10/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/apps/python/3.10/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/apps/python/3.10/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.wa

accuracy: 0.633 ± 0.003
recall_1: 0.837 ± 0.001
f1_1: 0.732 ± 0.002


In [4]:
from sklearn.metrics import confusion_matrix, recall_score, f1_score

proba = ada_clf.predict_proba(X_test)[:, 1]

for thr in [0.2, 0.3, 0.4, 0.5]:
    y_pred_thr = (proba >= thr).astype(int)
    print(f"\n=== Threshold = {thr} ===")
    print("Confusion:\n", confusion_matrix(y_test, y_pred_thr))
    print("recall_1:", recall_score(y_test, y_pred_thr, pos_label=1))
    print("f1_1:", f1_score(y_test, y_pred_thr, pos_label=1))



=== Threshold = 0.2 ===
Confusion:
 [[    0  8000]
 [    0 12000]]
recall_1: 1.0
f1_1: 0.75

=== Threshold = 0.3 ===
Confusion:
 [[    0  8000]
 [    0 12000]]
recall_1: 1.0
f1_1: 0.75

=== Threshold = 0.4 ===
Confusion:
 [[    0  8000]
 [    0 12000]]
recall_1: 1.0
f1_1: 0.75

=== Threshold = 0.5 ===
Confusion:
 [[2621 5379]
 [2027 9973]]
recall_1: 0.8310833333333333
f1_1: 0.7292336940625914
